# Generated by Django 3.0 on 2019-12-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_title', models.CharField(max_length=255)),
                ('first_lesson', models.CharField(max_length=100)),
                ('second_lesson', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('university_code', models.IntegerField()),
                ('university_category', models.CharField(default='State', max_length=255)),
                ('university_type', models.CharField(default='University', max_length=255)),
                ('university_email', models.CharField(max_length=100)),
                ('university_site', models.CharField(max_length=100)),
                ('military_dep', models.CharField(default='No', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='hello.City')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_code', models.CharField(max_length=10)),
                ('spec_title', models.CharField(max_length=255)),
                ('total_grant', models.IntegerField()),
                ('full_kz', models.IntegerField()),
                ('full_rus', models.IntegerField()),
                ('full_eng', models.IntegerField()),
                ('shortened_kz', models.IntegerField()),
                ('shortened_ru', models.IntegerField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_prof', to='hello.Profesion')),
            ],
        ),
        migrations.AddField(
            model_name='profesion',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univer_prof', to='hello.University'),
        ),
    ]
