# Generated by Django 3.0 on 2019-12-03 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=255, unique=True)),
                ('uni_code', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('uni_type', models.CharField(max_length=255)),
                ('military_department', models.CharField(max_length=5)),
                ('uni_email', models.CharField(max_length=255)),
                ('total_grant', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni_city', to='hello.City')),
            ],
        ),
    ]
