# Generated by Django 3.0 on 2019-12-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_professions', to='hello.University'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_specializations', to='hello.Profesion'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='hello.City'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_category',
            field=models.CharField(default='State', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_site',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(default='University', max_length=255, null=True),
        ),
    ]
