# Generated by Django 3.0 on 2019-12-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profession',
            old_name='university_professions',
            new_name='university',
        ),
    ]
