# Generated by Django 3.0 on 2019-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20191205_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
