# Generated by Django 3.0 on 2019-12-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20191210_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TUser',
        ),
    ]
