# Generated by Django 3.0 on 2019-12-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_tuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('profession', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('university_rating', models.IntegerField()),
            ],
        ),
    ]
