# Generated by Django 3.0 on 2019-12-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_tuserrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TUser',
        ),
        migrations.DeleteModel(
            name='TUserRating',
        ),
    ]
